export const dummy_data = {
  forecastday: [
    {
      date: "2023-08-08",
      date_epoch: 1691452800,
      day: {
        maxtemp_c: 18.0,
        maxtemp_f: 64.4,
        mintemp_c: 13.8,
        mintemp_f: 56.8,
        avgtemp_c: 15.6,
        avgtemp_f: 60.1,
        maxwind_mph: 17.7,
        maxwind_kph: 28.4,
        totalprecip_mm: 2.2,
        totalprecip_in: 0.09,
        totalsnow_cm: 0.0,
        avgvis_km: 10.0,
        avgvis_miles: 6.0,
        avghumidity: 74.0,
        daily_will_it_rain: 1,
        daily_chance_of_rain: 96,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: "Patchy rain possible",
          icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
          code: 1063,
        },
        uv: 4.0,
      },
      astro: {
        sunrise: "06:11 AM",
        sunset: "09:20 PM",
        moonrise: "11:54 PM",
        moonset: "03:12 PM",
        moon_phase: "Last Quarter",
        moon_illumination: "55",
        is_moon_up: 1,
        is_sun_up: 0,
      },
      hour: [
        {
          time_epoch: 1691445600,
          time: "2023-08-08 00:00",
          temp_c: 14.0,
          temp_f: 57.2,
          is_day: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
            code: 1063,
          },
          wind_mph: 8.3,
          wind_kph: 13.3,
          wind_degree: 257,
          wind_dir: "WSW",
          pressure_mb: 1014.0,
          pressure_in: 29.95,
          precip_mm: 0.1,
          precip_in: 0.0,
          humidity: 80,
          cloud: 81,
          feelslike_c: 13.0,
          feelslike_f: 55.4,
          windchill_c: 13.0,
          windchill_f: 55.4,
          heatindex_c: 14.0,
          heatindex_f: 57.2,
          dewpoint_c: 10.6,
          dewpoint_f: 51.1,
          will_it_rain: 0,
          chance_of_rain: 66,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.0,
          gust_kph: 27.4,
          uv: 1.0,
        },
        {
          time_epoch: 1691449200,
          time: "2023-08-08 01:00",
          temp_c: 13.8,
          temp_f: 56.8,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 8.5,
          wind_kph: 13.7,
          wind_degree: 261,
          wind_dir: "W",
          pressure_mb: 1014.0,
          pressure_in: 29.93,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 80,
          cloud: 22,
          feelslike_c: 12.8,
          feelslike_f: 55.0,
          windchill_c: 12.8,
          windchill_f: 55.0,
          heatindex_c: 13.8,
          heatindex_f: 56.8,
          dewpoint_c: 10.5,
          dewpoint_f: 50.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.4,
          gust_kph: 28.1,
          uv: 1.0,
        },
        {
          time_epoch: 1691452800,
          time: "2023-08-08 02:00",
          temp_c: 13.9,
          temp_f: 57.0,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 9.2,
          wind_kph: 14.8,
          wind_degree: 269,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.92,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 79,
          cloud: 24,
          feelslike_c: 12.8,
          feelslike_f: 55.0,
          windchill_c: 12.8,
          windchill_f: 55.0,
          heatindex_c: 13.9,
          heatindex_f: 57.0,
          dewpoint_c: 10.4,
          dewpoint_f: 50.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 18.3,
          gust_kph: 29.5,
          uv: 1.0,
        },
        {
          time_epoch: 1691456400,
          time: "2023-08-08 03:00",
          temp_c: 13.8,
          temp_f: 56.8,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 9.4,
          wind_kph: 15.1,
          wind_degree: 273,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.92,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 77,
          cloud: 32,
          feelslike_c: 12.6,
          feelslike_f: 54.7,
          windchill_c: 12.6,
          windchill_f: 54.7,
          heatindex_c: 13.8,
          heatindex_f: 56.8,
          dewpoint_c: 9.8,
          dewpoint_f: 49.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 18.6,
          gust_kph: 29.9,
          uv: 1.0,
        },
        {
          time_epoch: 1691460000,
          time: "2023-08-08 04:00",
          temp_c: 13.9,
          temp_f: 57.0,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 9.6,
          wind_kph: 15.5,
          wind_degree: 276,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 77,
          cloud: 23,
          feelslike_c: 12.7,
          feelslike_f: 54.9,
          windchill_c: 12.7,
          windchill_f: 54.9,
          heatindex_c: 13.9,
          heatindex_f: 57.0,
          dewpoint_c: 9.9,
          dewpoint_f: 49.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 18.8,
          gust_kph: 30.2,
          uv: 1.0,
        },
        {
          time_epoch: 1691463600,
          time: "2023-08-08 05:00",
          temp_c: 13.8,
          temp_f: 56.8,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 10.5,
          wind_kph: 16.9,
          wind_degree: 275,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 76,
          cloud: 40,
          feelslike_c: 12.5,
          feelslike_f: 54.5,
          windchill_c: 12.5,
          windchill_f: 54.5,
          heatindex_c: 13.8,
          heatindex_f: 56.8,
          dewpoint_c: 9.6,
          dewpoint_f: 49.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 19.9,
          gust_kph: 32.0,
          uv: 1.0,
        },
        {
          time_epoch: 1691467200,
          time: "2023-08-08 06:00",
          temp_c: 14.1,
          temp_f: 57.4,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 11.2,
          wind_kph: 18.0,
          wind_degree: 276,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 74,
          cloud: 35,
          feelslike_c: 12.7,
          feelslike_f: 54.9,
          windchill_c: 12.7,
          windchill_f: 54.9,
          heatindex_c: 14.1,
          heatindex_f: 57.4,
          dewpoint_c: 9.6,
          dewpoint_f: 49.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 19.9,
          gust_kph: 32.0,
          uv: 1.0,
        },
        {
          time_epoch: 1691470800,
          time: "2023-08-08 07:00",
          temp_c: 15.1,
          temp_f: 59.2,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 11.6,
          wind_kph: 18.7,
          wind_degree: 276,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 72,
          cloud: 37,
          feelslike_c: 15.1,
          feelslike_f: 59.2,
          windchill_c: 15.1,
          windchill_f: 59.2,
          heatindex_c: 15.1,
          heatindex_f: 59.2,
          dewpoint_c: 10.0,
          dewpoint_f: 50.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.9,
          gust_kph: 28.8,
          uv: 5.0,
        },
        {
          time_epoch: 1691474400,
          time: "2023-08-08 08:00",
          temp_c: 16.3,
          temp_f: 61.3,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 13.0,
          wind_kph: 20.9,
          wind_degree: 274,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 68,
          cloud: 42,
          feelslike_c: 16.3,
          feelslike_f: 61.3,
          windchill_c: 16.3,
          windchill_f: 61.3,
          heatindex_c: 16.3,
          heatindex_f: 61.3,
          dewpoint_c: 10.4,
          dewpoint_f: 50.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.0,
          gust_kph: 27.4,
          uv: 5.0,
        },
        {
          time_epoch: 1691478000,
          time: "2023-08-08 09:00",
          temp_c: 16.9,
          temp_f: 62.4,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 14.8,
          wind_kph: 23.8,
          wind_degree: 272,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 64,
          cloud: 54,
          feelslike_c: 16.9,
          feelslike_f: 62.4,
          windchill_c: 16.9,
          windchill_f: 62.4,
          heatindex_c: 16.9,
          heatindex_f: 62.4,
          dewpoint_c: 10.1,
          dewpoint_f: 50.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.7,
          gust_kph: 28.4,
          uv: 5.0,
        },
        {
          time_epoch: 1691481600,
          time: "2023-08-08 10:00",
          temp_c: 17.3,
          temp_f: 63.1,
          is_day: 1,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          wind_mph: 15.9,
          wind_kph: 25.6,
          wind_degree: 268,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.1,
          precip_in: 0.0,
          humidity: 63,
          cloud: 54,
          feelslike_c: 17.3,
          feelslike_f: 63.1,
          windchill_c: 17.3,
          windchill_f: 63.1,
          heatindex_c: 17.3,
          heatindex_f: 63.1,
          dewpoint_c: 10.2,
          dewpoint_f: 50.4,
          will_it_rain: 0,
          chance_of_rain: 65,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 18.3,
          gust_kph: 29.5,
          uv: 4.0,
        },
        {
          time_epoch: 1691485200,
          time: "2023-08-08 11:00",
          temp_c: 17.4,
          temp_f: 63.3,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 17.0,
          wind_kph: 27.4,
          wind_degree: 267,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 64,
          cloud: 52,
          feelslike_c: 17.4,
          feelslike_f: 63.3,
          windchill_c: 17.4,
          windchill_f: 63.3,
          heatindex_c: 17.4,
          heatindex_f: 63.3,
          dewpoint_c: 10.5,
          dewpoint_f: 50.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 19.5,
          gust_kph: 31.3,
          uv: 5.0,
        },
        {
          time_epoch: 1691488800,
          time: "2023-08-08 12:00",
          temp_c: 17.7,
          temp_f: 63.9,
          is_day: 1,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          wind_mph: 16.8,
          wind_kph: 27.0,
          wind_degree: 265,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.1,
          precip_in: 0.0,
          humidity: 63,
          cloud: 76,
          feelslike_c: 17.7,
          feelslike_f: 63.9,
          windchill_c: 17.7,
          windchill_f: 63.9,
          heatindex_c: 17.7,
          heatindex_f: 63.9,
          dewpoint_c: 10.5,
          dewpoint_f: 50.9,
          will_it_rain: 1,
          chance_of_rain: 82,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 20.1,
          gust_kph: 32.4,
          uv: 4.0,
        },
        {
          time_epoch: 1691492400,
          time: "2023-08-08 13:00",
          temp_c: 18.0,
          temp_f: 64.4,
          is_day: 1,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          wind_mph: 17.7,
          wind_kph: 28.4,
          wind_degree: 266,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.2,
          precip_in: 0.01,
          humidity: 62,
          cloud: 89,
          feelslike_c: 18.0,
          feelslike_f: 64.4,
          windchill_c: 18.0,
          windchill_f: 64.4,
          heatindex_c: 18.0,
          heatindex_f: 64.4,
          dewpoint_c: 10.6,
          dewpoint_f: 51.1,
          will_it_rain: 1,
          chance_of_rain: 95,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 9.0,
          vis_miles: 5.0,
          gust_mph: 20.6,
          gust_kph: 33.1,
          uv: 4.0,
        },
        {
          time_epoch: 1691496000,
          time: "2023-08-08 14:00",
          temp_c: 17.8,
          temp_f: 64.0,
          is_day: 1,
          condition: {
            text: "Light rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
            code: 1240,
          },
          wind_mph: 17.7,
          wind_kph: 28.4,
          wind_degree: 269,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.9,
          precip_mm: 0.2,
          precip_in: 0.01,
          humidity: 65,
          cloud: 60,
          feelslike_c: 17.8,
          feelslike_f: 64.0,
          windchill_c: 17.8,
          windchill_f: 64.0,
          heatindex_c: 17.8,
          heatindex_f: 64.0,
          dewpoint_c: 11.1,
          dewpoint_f: 52.0,
          will_it_rain: 1,
          chance_of_rain: 96,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 20.6,
          gust_kph: 33.1,
          uv: 4.0,
        },
        {
          time_epoch: 1691499600,
          time: "2023-08-08 15:00",
          temp_c: 17.7,
          temp_f: 63.9,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 16.8,
          wind_kph: 27.0,
          wind_degree: 271,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 66,
          cloud: 54,
          feelslike_c: 17.7,
          feelslike_f: 63.9,
          windchill_c: 17.7,
          windchill_f: 63.9,
          heatindex_c: 17.7,
          heatindex_f: 63.9,
          dewpoint_c: 11.3,
          dewpoint_f: 52.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 19.2,
          gust_kph: 31.0,
          uv: 5.0,
        },
        {
          time_epoch: 1691503200,
          time: "2023-08-08 16:00",
          temp_c: 17.5,
          temp_f: 63.5,
          is_day: 1,
          condition: {
            text: "Light rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
            code: 1240,
          },
          wind_mph: 15.7,
          wind_kph: 25.2,
          wind_degree: 268,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.7,
          precip_in: 0.03,
          humidity: 67,
          cloud: 82,
          feelslike_c: 17.5,
          feelslike_f: 63.5,
          windchill_c: 17.5,
          windchill_f: 63.5,
          heatindex_c: 17.5,
          heatindex_f: 63.5,
          dewpoint_c: 11.4,
          dewpoint_f: 52.5,
          will_it_rain: 1,
          chance_of_rain: 95,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 19.7,
          gust_kph: 31.7,
          uv: 4.0,
        },
        {
          time_epoch: 1691506800,
          time: "2023-08-08 17:00",
          temp_c: 16.2,
          temp_f: 61.2,
          is_day: 1,
          condition: {
            text: "Overcast",
            icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
            code: 1009,
          },
          wind_mph: 13.0,
          wind_kph: 20.9,
          wind_degree: 269,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 77,
          cloud: 100,
          feelslike_c: 16.2,
          feelslike_f: 61.2,
          windchill_c: 16.2,
          windchill_f: 61.2,
          heatindex_c: 16.2,
          heatindex_f: 61.2,
          dewpoint_c: 12.1,
          dewpoint_f: 53.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 17.2,
          gust_kph: 27.7,
          uv: 4.0,
        },
        {
          time_epoch: 1691510400,
          time: "2023-08-08 18:00",
          temp_c: 15.3,
          temp_f: 59.5,
          is_day: 1,
          condition: {
            text: "Light rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
            code: 1240,
          },
          wind_mph: 10.1,
          wind_kph: 16.2,
          wind_degree: 270,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.2,
          precip_in: 0.01,
          humidity: 81,
          cloud: 100,
          feelslike_c: 15.3,
          feelslike_f: 59.5,
          windchill_c: 15.3,
          windchill_f: 59.5,
          heatindex_c: 15.3,
          heatindex_f: 59.5,
          dewpoint_c: 12.1,
          dewpoint_f: 53.8,
          will_it_rain: 1,
          chance_of_rain: 94,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 15.4,
          gust_kph: 24.8,
          uv: 4.0,
        },
        {
          time_epoch: 1691514000,
          time: "2023-08-08 19:00",
          temp_c: 15.1,
          temp_f: 59.2,
          is_day: 1,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          wind_mph: 8.9,
          wind_kph: 14.4,
          wind_degree: 271,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.1,
          precip_in: 0.0,
          humidity: 82,
          cloud: 96,
          feelslike_c: 15.1,
          feelslike_f: 59.2,
          windchill_c: 15.1,
          windchill_f: 59.2,
          heatindex_c: 15.1,
          heatindex_f: 59.2,
          dewpoint_c: 12.1,
          dewpoint_f: 53.8,
          will_it_rain: 1,
          chance_of_rain: 75,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.9,
          gust_kph: 22.3,
          uv: 4.0,
        },
        {
          time_epoch: 1691517600,
          time: "2023-08-08 20:00",
          temp_c: 14.9,
          temp_f: 58.8,
          is_day: 1,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          wind_mph: 7.8,
          wind_kph: 12.6,
          wind_degree: 272,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.1,
          precip_in: 0.0,
          humidity: 83,
          cloud: 76,
          feelslike_c: 14.2,
          feelslike_f: 57.6,
          windchill_c: 14.2,
          windchill_f: 57.6,
          heatindex_c: 14.9,
          heatindex_f: 58.8,
          dewpoint_c: 12.1,
          dewpoint_f: 53.8,
          will_it_rain: 1,
          chance_of_rain: 72,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 12.3,
          gust_kph: 19.8,
          uv: 3.0,
        },
        {
          time_epoch: 1691521200,
          time: "2023-08-08 21:00",
          temp_c: 14.8,
          temp_f: 58.6,
          is_day: 1,
          condition: {
            text: "Cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
            code: 1006,
          },
          wind_mph: 6.9,
          wind_kph: 11.2,
          wind_degree: 265,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 85,
          cloud: 63,
          feelslike_c: 14.2,
          feelslike_f: 57.6,
          windchill_c: 14.2,
          windchill_f: 57.6,
          heatindex_c: 14.8,
          heatindex_f: 58.6,
          dewpoint_c: 12.2,
          dewpoint_f: 54.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 11.2,
          gust_kph: 18.0,
          uv: 3.0,
        },
        {
          time_epoch: 1691524800,
          time: "2023-08-08 22:00",
          temp_c: 14.6,
          temp_f: 58.3,
          is_day: 0,
          condition: {
            text: "Light rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
            code: 1240,
          },
          wind_mph: 6.3,
          wind_kph: 10.1,
          wind_degree: 267,
          wind_dir: "W",
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.4,
          precip_in: 0.02,
          humidity: 87,
          cloud: 55,
          feelslike_c: 14.2,
          feelslike_f: 57.6,
          windchill_c: 14.2,
          windchill_f: 57.6,
          heatindex_c: 14.6,
          heatindex_f: 58.3,
          dewpoint_c: 12.5,
          dewpoint_f: 54.5,
          will_it_rain: 0,
          chance_of_rain: 65,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.3,
          gust_kph: 16.6,
          uv: 1.0,
        },
        {
          time_epoch: 1691528400,
          time: "2023-08-08 23:00",
          temp_c: 14.3,
          temp_f: 57.7,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 284,
          wind_dir: "WNW",
          pressure_mb: 1012.0,
          pressure_in: 29.88,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 89,
          cloud: 41,
          feelslike_c: 13.9,
          feelslike_f: 57.0,
          windchill_c: 13.9,
          windchill_f: 57.0,
          heatindex_c: 14.3,
          heatindex_f: 57.7,
          dewpoint_c: 12.5,
          dewpoint_f: 54.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.4,
          gust_kph: 15.1,
          uv: 1.0,
        },
      ],
    },
    {
      date: "2023-08-09",
      date_epoch: 1691539200,
      day: {
        maxtemp_c: 19.9,
        maxtemp_f: 67.8,
        mintemp_c: 12.5,
        mintemp_f: 54.5,
        avgtemp_c: 15.7,
        avgtemp_f: 60.3,
        maxwind_mph: 11.6,
        maxwind_kph: 18.7,
        totalprecip_mm: 0.2,
        totalprecip_in: 0.01,
        totalsnow_cm: 0.0,
        avgvis_km: 10.0,
        avgvis_miles: 6.0,
        avghumidity: 72.0,
        daily_will_it_rain: 0,
        daily_chance_of_rain: 69,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: "Patchy rain possible",
          icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
          code: 1063,
        },
        uv: 4.0,
      },
      astro: {
        sunrise: "06:13 AM",
        sunset: "09:18 PM",
        moonrise: "No moonrise",
        moonset: "04:34 PM",
        moon_phase: "Waning Crescent",
        moon_illumination: "44",
        is_moon_up: 1,
        is_sun_up: 0,
      },
      hour: [
        {
          time_epoch: 1691532000,
          time: "2023-08-09 00:00",
          temp_c: 13.7,
          temp_f: 56.7,
          is_day: 0,
          condition: {
            text: "Light rain shower",
            icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
            code: 1240,
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 291,
          wind_dir: "WNW",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.2,
          precip_in: 0.01,
          humidity: 91,
          cloud: 52,
          feelslike_c: 13.5,
          feelslike_f: 56.3,
          windchill_c: 13.5,
          windchill_f: 56.3,
          heatindex_c: 13.7,
          heatindex_f: 56.7,
          dewpoint_c: 12.2,
          dewpoint_f: 54.0,
          will_it_rain: 0,
          chance_of_rain: 69,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.1,
          gust_kph: 13.0,
          uv: 1.0,
        },
        {
          time_epoch: 1691535600,
          time: "2023-08-09 01:00",
          temp_c: 13.1,
          temp_f: 55.6,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 289,
          wind_dir: "WNW",
          pressure_mb: 1012.0,
          pressure_in: 29.89,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 91,
          cloud: 31,
          feelslike_c: 13.1,
          feelslike_f: 55.6,
          windchill_c: 13.1,
          windchill_f: 55.6,
          heatindex_c: 13.1,
          heatindex_f: 55.6,
          dewpoint_c: 11.6,
          dewpoint_f: 52.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.2,
          gust_kph: 11.5,
          uv: 1.0,
        },
        {
          time_epoch: 1691539200,
          time: "2023-08-09 02:00",
          temp_c: 12.8,
          temp_f: 55.0,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 285,
          wind_dir: "WNW",
          pressure_mb: 1013.0,
          pressure_in: 29.9,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 90,
          cloud: 31,
          feelslike_c: 12.7,
          feelslike_f: 54.9,
          windchill_c: 12.7,
          windchill_f: 54.9,
          heatindex_c: 12.8,
          heatindex_f: 55.0,
          dewpoint_c: 11.2,
          dewpoint_f: 52.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.4,
          gust_kph: 11.9,
          uv: 1.0,
        },
        {
          time_epoch: 1691542800,
          time: "2023-08-09 03:00",
          temp_c: 12.6,
          temp_f: 54.7,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.9,
          wind_kph: 4.7,
          wind_degree: 282,
          wind_dir: "WNW",
          pressure_mb: 1013.0,
          pressure_in: 29.91,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 89,
          cloud: 25,
          feelslike_c: 12.8,
          feelslike_f: 55.0,
          windchill_c: 12.8,
          windchill_f: 55.0,
          heatindex_c: 12.6,
          heatindex_f: 54.7,
          dewpoint_c: 10.9,
          dewpoint_f: 51.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.0,
          gust_kph: 9.7,
          uv: 1.0,
        },
        {
          time_epoch: 1691546400,
          time: "2023-08-09 04:00",
          temp_c: 12.6,
          temp_f: 54.7,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.9,
          wind_kph: 4.7,
          wind_degree: 260,
          wind_dir: "W",
          pressure_mb: 1013.0,
          pressure_in: 29.91,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 89,
          cloud: 13,
          feelslike_c: 12.7,
          feelslike_f: 54.9,
          windchill_c: 12.7,
          windchill_f: 54.9,
          heatindex_c: 12.6,
          heatindex_f: 54.7,
          dewpoint_c: 10.8,
          dewpoint_f: 51.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.0,
          gust_kph: 9.7,
          uv: 1.0,
        },
        {
          time_epoch: 1691550000,
          time: "2023-08-09 05:00",
          temp_c: 12.5,
          temp_f: 54.5,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 3.1,
          wind_kph: 5.0,
          wind_degree: 248,
          wind_dir: "WSW",
          pressure_mb: 1013.0,
          pressure_in: 29.93,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 89,
          cloud: 7,
          feelslike_c: 12.5,
          feelslike_f: 54.5,
          windchill_c: 12.5,
          windchill_f: 54.5,
          heatindex_c: 12.4,
          heatindex_f: 54.3,
          dewpoint_c: 10.6,
          dewpoint_f: 51.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.5,
          gust_kph: 10.4,
          uv: 1.0,
        },
        {
          time_epoch: 1691553600,
          time: "2023-08-09 06:00",
          temp_c: 12.9,
          temp_f: 55.2,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 3.4,
          wind_kph: 5.4,
          wind_degree: 242,
          wind_dir: "WSW",
          pressure_mb: 1014.0,
          pressure_in: 29.93,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 88,
          cloud: 3,
          feelslike_c: 12.9,
          feelslike_f: 55.2,
          windchill_c: 12.9,
          windchill_f: 55.2,
          heatindex_c: 12.9,
          heatindex_f: 55.2,
          dewpoint_c: 10.9,
          dewpoint_f: 51.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.9,
          gust_kph: 11.2,
          uv: 1.0,
        },
        {
          time_epoch: 1691557200,
          time: "2023-08-09 07:00",
          temp_c: 14.4,
          temp_f: 57.9,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 3.1,
          wind_kph: 5.0,
          wind_degree: 258,
          wind_dir: "WSW",
          pressure_mb: 1014.0,
          pressure_in: 29.95,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 84,
          cloud: 16,
          feelslike_c: 14.7,
          feelslike_f: 58.5,
          windchill_c: 14.7,
          windchill_f: 58.5,
          heatindex_c: 14.4,
          heatindex_f: 57.9,
          dewpoint_c: 11.8,
          dewpoint_f: 53.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.4,
          gust_kph: 8.6,
          uv: 4.0,
        },
        {
          time_epoch: 1691560800,
          time: "2023-08-09 08:00",
          temp_c: 16.2,
          temp_f: 61.2,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 278,
          wind_dir: "W",
          pressure_mb: 1015.0,
          pressure_in: 29.96,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 76,
          cloud: 46,
          feelslike_c: 16.2,
          feelslike_f: 61.2,
          windchill_c: 16.2,
          windchill_f: 61.2,
          heatindex_c: 16.2,
          heatindex_f: 61.2,
          dewpoint_c: 11.9,
          dewpoint_f: 53.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.4,
          gust_kph: 8.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691564400,
          time: "2023-08-09 09:00",
          temp_c: 17.4,
          temp_f: 63.3,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 5.4,
          wind_kph: 8.6,
          wind_degree: 289,
          wind_dir: "WNW",
          pressure_mb: 1015.0,
          pressure_in: 29.98,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 65,
          cloud: 47,
          feelslike_c: 17.4,
          feelslike_f: 63.3,
          windchill_c: 17.4,
          windchill_f: 63.3,
          heatindex_c: 17.4,
          heatindex_f: 63.3,
          dewpoint_c: 10.8,
          dewpoint_f: 51.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.9,
          gust_kph: 11.2,
          uv: 5.0,
        },
        {
          time_epoch: 1691568000,
          time: "2023-08-09 10:00",
          temp_c: 18.3,
          temp_f: 64.9,
          is_day: 1,
          condition: {
            text: "Cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
            code: 1006,
          },
          wind_mph: 7.2,
          wind_kph: 11.5,
          wind_degree: 292,
          wind_dir: "WNW",
          pressure_mb: 1016.0,
          pressure_in: 29.99,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 57,
          cloud: 72,
          feelslike_c: 18.3,
          feelslike_f: 64.9,
          windchill_c: 18.3,
          windchill_f: 64.9,
          heatindex_c: 18.3,
          heatindex_f: 64.9,
          dewpoint_c: 9.7,
          dewpoint_f: 49.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.5,
          gust_kph: 13.7,
          uv: 4.0,
        },
        {
          time_epoch: 1691571600,
          time: "2023-08-09 11:00",
          temp_c: 19.2,
          temp_f: 66.6,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 8.7,
          wind_kph: 14.0,
          wind_degree: 291,
          wind_dir: "WNW",
          pressure_mb: 1016.0,
          pressure_in: 30.01,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 54,
          cloud: 44,
          feelslike_c: 19.2,
          feelslike_f: 66.6,
          windchill_c: 19.2,
          windchill_f: 66.6,
          heatindex_c: 19.2,
          heatindex_f: 66.6,
          dewpoint_c: 9.6,
          dewpoint_f: 49.3,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 10.1,
          gust_kph: 16.2,
          uv: 5.0,
        },
        {
          time_epoch: 1691575200,
          time: "2023-08-09 12:00",
          temp_c: 19.6,
          temp_f: 67.3,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 9.8,
          wind_kph: 15.8,
          wind_degree: 286,
          wind_dir: "WNW",
          pressure_mb: 1017.0,
          pressure_in: 30.02,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 53,
          cloud: 21,
          feelslike_c: 19.6,
          feelslike_f: 67.3,
          windchill_c: 19.6,
          windchill_f: 67.3,
          heatindex_c: 19.6,
          heatindex_f: 67.3,
          dewpoint_c: 9.7,
          dewpoint_f: 49.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 11.4,
          gust_kph: 18.4,
          uv: 5.0,
        },
        {
          time_epoch: 1691578800,
          time: "2023-08-09 13:00",
          temp_c: 19.9,
          temp_f: 67.8,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 11.2,
          wind_kph: 18.0,
          wind_degree: 285,
          wind_dir: "WNW",
          pressure_mb: 1017.0,
          pressure_in: 30.04,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 53,
          cloud: 46,
          feelslike_c: 19.9,
          feelslike_f: 67.8,
          windchill_c: 19.9,
          windchill_f: 67.8,
          heatindex_c: 19.9,
          heatindex_f: 67.8,
          dewpoint_c: 10.1,
          dewpoint_f: 50.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.0,
          gust_kph: 20.9,
          uv: 5.0,
        },
        {
          time_epoch: 1691582400,
          time: "2023-08-09 14:00",
          temp_c: 19.7,
          temp_f: 67.5,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 11.6,
          wind_kph: 18.7,
          wind_degree: 285,
          wind_dir: "WNW",
          pressure_mb: 1018.0,
          pressure_in: 30.05,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 55,
          cloud: 17,
          feelslike_c: 19.7,
          feelslike_f: 67.5,
          windchill_c: 19.7,
          windchill_f: 67.5,
          heatindex_c: 19.7,
          heatindex_f: 67.5,
          dewpoint_c: 10.3,
          dewpoint_f: 50.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.4,
          gust_kph: 21.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691586000,
          time: "2023-08-09 15:00",
          temp_c: 19.3,
          temp_f: 66.7,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 11.6,
          wind_kph: 18.7,
          wind_degree: 291,
          wind_dir: "WNW",
          pressure_mb: 1018.0,
          pressure_in: 30.06,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 55,
          cloud: 5,
          feelslike_c: 19.3,
          feelslike_f: 66.7,
          windchill_c: 19.3,
          windchill_f: 66.7,
          heatindex_c: 19.3,
          heatindex_f: 66.7,
          dewpoint_c: 10.0,
          dewpoint_f: 50.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.4,
          gust_kph: 21.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691589600,
          time: "2023-08-09 16:00",
          temp_c: 18.8,
          temp_f: 65.8,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 11.6,
          wind_kph: 18.7,
          wind_degree: 292,
          wind_dir: "WNW",
          pressure_mb: 1018.0,
          pressure_in: 30.07,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 55,
          cloud: 4,
          feelslike_c: 18.8,
          feelslike_f: 65.8,
          windchill_c: 18.8,
          windchill_f: 65.8,
          heatindex_c: 18.8,
          heatindex_f: 65.8,
          dewpoint_c: 9.5,
          dewpoint_f: 49.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.4,
          gust_kph: 21.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691593200,
          time: "2023-08-09 17:00",
          temp_c: 18.1,
          temp_f: 64.6,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 11.0,
          wind_kph: 17.6,
          wind_degree: 299,
          wind_dir: "WNW",
          pressure_mb: 1019.0,
          pressure_in: 30.09,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 55,
          cloud: 4,
          feelslike_c: 18.1,
          feelslike_f: 64.6,
          windchill_c: 18.1,
          windchill_f: 64.6,
          heatindex_c: 18.1,
          heatindex_f: 64.6,
          dewpoint_c: 9.0,
          dewpoint_f: 48.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 13.0,
          gust_kph: 20.9,
          uv: 5.0,
        },
        {
          time_epoch: 1691596800,
          time: "2023-08-09 18:00",
          temp_c: 17.3,
          temp_f: 63.1,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 9.6,
          wind_kph: 15.5,
          wind_degree: 306,
          wind_dir: "NW",
          pressure_mb: 1019.0,
          pressure_in: 30.1,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 58,
          cloud: 6,
          feelslike_c: 17.3,
          feelslike_f: 63.1,
          windchill_c: 17.3,
          windchill_f: 63.1,
          heatindex_c: 17.3,
          heatindex_f: 63.1,
          dewpoint_c: 9.0,
          dewpoint_f: 48.2,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 12.3,
          gust_kph: 19.8,
          uv: 5.0,
        },
        {
          time_epoch: 1691600400,
          time: "2023-08-09 19:00",
          temp_c: 16.3,
          temp_f: 61.3,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 7.6,
          wind_kph: 12.2,
          wind_degree: 309,
          wind_dir: "NW",
          pressure_mb: 1020.0,
          pressure_in: 30.12,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 65,
          cloud: 5,
          feelslike_c: 16.3,
          feelslike_f: 61.3,
          windchill_c: 16.3,
          windchill_f: 61.3,
          heatindex_c: 16.3,
          heatindex_f: 61.3,
          dewpoint_c: 9.7,
          dewpoint_f: 49.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 11.0,
          gust_kph: 17.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691604000,
          time: "2023-08-09 20:00",
          temp_c: 14.4,
          temp_f: 57.9,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 4.7,
          wind_kph: 7.6,
          wind_degree: 317,
          wind_dir: "NW",
          pressure_mb: 1020.0,
          pressure_in: 30.13,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 74,
          cloud: 6,
          feelslike_c: 14.2,
          feelslike_f: 57.6,
          windchill_c: 14.2,
          windchill_f: 57.6,
          heatindex_c: 14.4,
          heatindex_f: 57.9,
          dewpoint_c: 9.7,
          dewpoint_f: 49.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 8.5,
          gust_kph: 13.7,
          uv: 4.0,
        },
        {
          time_epoch: 1691607600,
          time: "2023-08-09 21:00",
          temp_c: 13.2,
          temp_f: 55.8,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 3.1,
          wind_kph: 5.0,
          wind_degree: 322,
          wind_dir: "NW",
          pressure_mb: 1021.0,
          pressure_in: 30.14,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 78,
          cloud: 6,
          feelslike_c: 13.4,
          feelslike_f: 56.1,
          windchill_c: 13.4,
          windchill_f: 56.1,
          heatindex_c: 13.2,
          heatindex_f: 55.8,
          dewpoint_c: 9.5,
          dewpoint_f: 49.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.3,
          gust_kph: 10.1,
          uv: 4.0,
        },
        {
          time_epoch: 1691611200,
          time: "2023-08-09 22:00",
          temp_c: 12.8,
          temp_f: 55.0,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.5,
          wind_kph: 4.0,
          wind_degree: 300,
          wind_dir: "WNW",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 80,
          cloud: 10,
          feelslike_c: 13.2,
          feelslike_f: 55.8,
          windchill_c: 13.2,
          windchill_f: 55.8,
          heatindex_c: 12.8,
          heatindex_f: 55.0,
          dewpoint_c: 9.3,
          dewpoint_f: 48.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.9,
          gust_kph: 7.9,
          uv: 1.0,
        },
        {
          time_epoch: 1691614800,
          time: "2023-08-09 23:00",
          temp_c: 12.6,
          temp_f: 54.7,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 2.0,
          wind_kph: 3.2,
          wind_degree: 283,
          wind_dir: "WNW",
          pressure_mb: 1021.0,
          pressure_in: 30.16,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 79,
          cloud: 26,
          feelslike_c: 13.2,
          feelslike_f: 55.8,
          windchill_c: 13.2,
          windchill_f: 55.8,
          heatindex_c: 12.6,
          heatindex_f: 54.7,
          dewpoint_c: 9.1,
          dewpoint_f: 48.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.3,
          gust_kph: 6.8,
          uv: 1.0,
        },
      ],
    },
    {
      date: "2023-08-10",
      date_epoch: 1691625600,
      day: {
        maxtemp_c: 23.6,
        maxtemp_f: 74.5,
        mintemp_c: 12.0,
        mintemp_f: 53.6,
        avgtemp_c: 17.7,
        avgtemp_f: 63.9,
        maxwind_mph: 4.5,
        maxwind_kph: 7.2,
        totalprecip_mm: 0.0,
        totalprecip_in: 0.0,
        totalsnow_cm: 0.0,
        avgvis_km: 10.0,
        avgvis_miles: 6.0,
        avghumidity: 65.0,
        daily_will_it_rain: 0,
        daily_chance_of_rain: 0,
        daily_will_it_snow: 0,
        daily_chance_of_snow: 0,
        condition: {
          text: "Sunny",
          icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
          code: 1000,
        },
        uv: 5.0,
      },
      astro: {
        sunrise: "06:14 AM",
        sunset: "09:16 PM",
        moonrise: "12:16 AM",
        moonset: "05:51 PM",
        moon_phase: "Waning Crescent",
        moon_illumination: "34",
        is_moon_up: 1,
        is_sun_up: 0,
      },
      hour: [
        {
          time_epoch: 1691618400,
          time: "2023-08-10 00:00",
          temp_c: 12.4,
          temp_f: 54.3,
          is_day: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
          },
          wind_mph: 1.6,
          wind_kph: 2.5,
          wind_degree: 270,
          wind_dir: "W",
          pressure_mb: 1022.0,
          pressure_in: 30.16,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 79,
          cloud: 29,
          feelslike_c: 12.4,
          feelslike_f: 54.3,
          windchill_c: 12.4,
          windchill_f: 54.3,
          heatindex_c: 12.4,
          heatindex_f: 54.3,
          dewpoint_c: 8.8,
          dewpoint_f: 47.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 3.4,
          gust_kph: 5.4,
          uv: 1.0,
        },
        {
          time_epoch: 1691622000,
          time: "2023-08-10 01:00",
          temp_c: 12.3,
          temp_f: 54.1,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 1.6,
          wind_kph: 2.5,
          wind_degree: 235,
          wind_dir: "SW",
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 78,
          cloud: 15,
          feelslike_c: 12.3,
          feelslike_f: 54.1,
          windchill_c: 12.3,
          windchill_f: 54.1,
          heatindex_c: 12.3,
          heatindex_f: 54.1,
          dewpoint_c: 8.6,
          dewpoint_f: 47.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 3.4,
          gust_kph: 5.4,
          uv: 1.0,
        },
        {
          time_epoch: 1691625600,
          time: "2023-08-10 02:00",
          temp_c: 12.3,
          temp_f: 54.1,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.5,
          wind_kph: 4.0,
          wind_degree: 228,
          wind_dir: "SW",
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 77,
          cloud: 15,
          feelslike_c: 12.6,
          feelslike_f: 54.7,
          windchill_c: 12.6,
          windchill_f: 54.7,
          heatindex_c: 12.2,
          heatindex_f: 54.0,
          dewpoint_c: 8.4,
          dewpoint_f: 47.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.1,
          gust_kph: 8.3,
          uv: 1.0,
        },
        {
          time_epoch: 1691629200,
          time: "2023-08-10 03:00",
          temp_c: 12.2,
          temp_f: 54.0,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.2,
          wind_kph: 3.6,
          wind_degree: 224,
          wind_dir: "SW",
          pressure_mb: 1022.0,
          pressure_in: 30.18,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 77,
          cloud: 20,
          feelslike_c: 12.7,
          feelslike_f: 54.9,
          windchill_c: 12.7,
          windchill_f: 54.9,
          heatindex_c: 12.2,
          heatindex_f: 54.0,
          dewpoint_c: 8.2,
          dewpoint_f: 46.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.7,
          gust_kph: 7.6,
          uv: 1.0,
        },
        {
          time_epoch: 1691632800,
          time: "2023-08-10 04:00",
          temp_c: 12.1,
          temp_f: 53.8,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 2.7,
          wind_kph: 4.3,
          wind_degree: 200,
          wind_dir: "SSW",
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 76,
          cloud: 22,
          feelslike_c: 12.3,
          feelslike_f: 54.1,
          windchill_c: 12.3,
          windchill_f: 54.1,
          heatindex_c: 12.1,
          heatindex_f: 53.8,
          dewpoint_c: 8.1,
          dewpoint_f: 46.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.6,
          gust_kph: 9.0,
          uv: 1.0,
        },
        {
          time_epoch: 1691636400,
          time: "2023-08-10 05:00",
          temp_c: 12.0,
          temp_f: 53.6,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 3.1,
          wind_kph: 5.0,
          wind_degree: 193,
          wind_dir: "SSW",
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 76,
          cloud: 22,
          feelslike_c: 12.0,
          feelslike_f: 53.6,
          windchill_c: 12.0,
          windchill_f: 53.6,
          heatindex_c: 12.0,
          heatindex_f: 53.6,
          dewpoint_c: 8.0,
          dewpoint_f: 46.4,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.5,
          gust_kph: 10.4,
          uv: 1.0,
        },
        {
          time_epoch: 1691640000,
          time: "2023-08-10 06:00",
          temp_c: 12.3,
          temp_f: 54.1,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 3.1,
          wind_kph: 5.0,
          wind_degree: 184,
          wind_dir: "S",
          pressure_mb: 1022.0,
          pressure_in: 30.18,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 76,
          cloud: 25,
          feelslike_c: 12.4,
          feelslike_f: 54.3,
          windchill_c: 12.4,
          windchill_f: 54.3,
          heatindex_c: 12.3,
          heatindex_f: 54.1,
          dewpoint_c: 8.2,
          dewpoint_f: 46.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 6.3,
          gust_kph: 10.1,
          uv: 1.0,
        },
        {
          time_epoch: 1691643600,
          time: "2023-08-10 07:00",
          temp_c: 14.1,
          temp_f: 57.4,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 2.9,
          wind_kph: 4.7,
          wind_degree: 181,
          wind_dir: "S",
          pressure_mb: 1022.0,
          pressure_in: 30.19,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 70,
          cloud: 26,
          feelslike_c: 14.4,
          feelslike_f: 57.9,
          windchill_c: 14.4,
          windchill_f: 57.9,
          heatindex_c: 14.1,
          heatindex_f: 57.4,
          dewpoint_c: 8.7,
          dewpoint_f: 47.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.5,
          gust_kph: 7.2,
          uv: 4.0,
        },
        {
          time_epoch: 1691647200,
          time: "2023-08-10 08:00",
          temp_c: 15.9,
          temp_f: 60.6,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 195,
          wind_dir: "SSW",
          pressure_mb: 1022.0,
          pressure_in: 30.19,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 63,
          cloud: 37,
          feelslike_c: 15.9,
          feelslike_f: 60.6,
          windchill_c: 15.9,
          windchill_f: 60.6,
          heatindex_c: 15.9,
          heatindex_f: 60.6,
          dewpoint_c: 8.9,
          dewpoint_f: 48.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.9,
          gust_kph: 7.9,
          uv: 5.0,
        },
        {
          time_epoch: 1691650800,
          time: "2023-08-10 09:00",
          temp_c: 17.7,
          temp_f: 63.9,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 201,
          wind_dir: "SSW",
          pressure_mb: 1023.0,
          pressure_in: 30.2,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 58,
          cloud: 30,
          feelslike_c: 17.7,
          feelslike_f: 63.9,
          windchill_c: 17.7,
          windchill_f: 63.9,
          heatindex_c: 17.7,
          heatindex_f: 63.9,
          dewpoint_c: 9.3,
          dewpoint_f: 48.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 5.4,
          gust_kph: 8.6,
          uv: 5.0,
        },
        {
          time_epoch: 1691654400,
          time: "2023-08-10 10:00",
          temp_c: 19.3,
          temp_f: 66.7,
          is_day: 1,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 208,
          wind_dir: "SSW",
          pressure_mb: 1022.0,
          pressure_in: 30.19,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 54,
          cloud: 31,
          feelslike_c: 19.3,
          feelslike_f: 66.7,
          windchill_c: 19.3,
          windchill_f: 66.7,
          heatindex_c: 19.3,
          heatindex_f: 66.7,
          dewpoint_c: 9.8,
          dewpoint_f: 49.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.9,
          gust_kph: 7.9,
          uv: 5.0,
        },
        {
          time_epoch: 1691658000,
          time: "2023-08-10 11:00",
          temp_c: 20.8,
          temp_f: 69.4,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 215,
          wind_dir: "SW",
          pressure_mb: 1022.0,
          pressure_in: 30.19,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 52,
          cloud: 17,
          feelslike_c: 20.8,
          feelslike_f: 69.4,
          windchill_c: 20.8,
          windchill_f: 69.4,
          heatindex_c: 20.8,
          heatindex_f: 69.4,
          dewpoint_c: 10.5,
          dewpoint_f: 50.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.7,
          gust_kph: 7.6,
          uv: 6.0,
        },
        {
          time_epoch: 1691661600,
          time: "2023-08-10 12:00",
          temp_c: 22.0,
          temp_f: 71.6,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 4.0,
          wind_kph: 6.5,
          wind_degree: 226,
          wind_dir: "SW",
          pressure_mb: 1022.0,
          pressure_in: 30.18,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 50,
          cloud: 25,
          feelslike_c: 24.4,
          feelslike_f: 75.9,
          windchill_c: 22.0,
          windchill_f: 71.6,
          heatindex_c: 24.4,
          heatindex_f: 75.9,
          dewpoint_c: 11.1,
          dewpoint_f: 52.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.7,
          gust_kph: 7.6,
          uv: 6.0,
        },
        {
          time_epoch: 1691665200,
          time: "2023-08-10 13:00",
          temp_c: 22.8,
          temp_f: 73.0,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 3.8,
          wind_kph: 6.1,
          wind_degree: 241,
          wind_dir: "WSW",
          pressure_mb: 1022.0,
          pressure_in: 30.17,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 49,
          cloud: 21,
          feelslike_c: 24.6,
          feelslike_f: 76.3,
          windchill_c: 22.8,
          windchill_f: 73.0,
          heatindex_c: 24.6,
          heatindex_f: 76.3,
          dewpoint_c: 11.6,
          dewpoint_f: 52.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.5,
          gust_kph: 7.2,
          uv: 6.0,
        },
        {
          time_epoch: 1691668800,
          time: "2023-08-10 14:00",
          temp_c: 23.3,
          temp_f: 73.9,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 4.3,
          wind_kph: 6.8,
          wind_degree: 252,
          wind_dir: "WSW",
          pressure_mb: 1022.0,
          pressure_in: 30.16,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 49,
          cloud: 14,
          feelslike_c: 24.8,
          feelslike_f: 76.6,
          windchill_c: 23.3,
          windchill_f: 73.9,
          heatindex_c: 24.8,
          heatindex_f: 76.6,
          dewpoint_c: 12.0,
          dewpoint_f: 53.6,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.9,
          gust_kph: 7.9,
          uv: 6.0,
        },
        {
          time_epoch: 1691672400,
          time: "2023-08-10 15:00",
          temp_c: 23.5,
          temp_f: 74.3,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 2.5,
          wind_kph: 4.0,
          wind_degree: 264,
          wind_dir: "W",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 49,
          cloud: 9,
          feelslike_c: 24.9,
          feelslike_f: 76.8,
          windchill_c: 23.5,
          windchill_f: 74.3,
          heatindex_c: 24.9,
          heatindex_f: 76.8,
          dewpoint_c: 12.3,
          dewpoint_f: 54.1,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 2.9,
          gust_kph: 4.7,
          uv: 6.0,
        },
        {
          time_epoch: 1691676000,
          time: "2023-08-10 16:00",
          temp_c: 23.6,
          temp_f: 74.5,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 1.6,
          wind_kph: 2.5,
          wind_degree: 311,
          wind_dir: "NW",
          pressure_mb: 1021.0,
          pressure_in: 30.14,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 50,
          cloud: 7,
          feelslike_c: 25.0,
          feelslike_f: 77.0,
          windchill_c: 23.6,
          windchill_f: 74.5,
          heatindex_c: 25.0,
          heatindex_f: 77.0,
          dewpoint_c: 12.6,
          dewpoint_f: 54.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 1.8,
          gust_kph: 2.9,
          uv: 6.0,
        },
        {
          time_epoch: 1691679600,
          time: "2023-08-10 17:00",
          temp_c: 23.2,
          temp_f: 73.8,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 2.0,
          wind_kph: 3.2,
          wind_degree: 300,
          wind_dir: "WNW",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 52,
          cloud: 8,
          feelslike_c: 24.9,
          feelslike_f: 76.8,
          windchill_c: 23.2,
          windchill_f: 73.8,
          heatindex_c: 24.9,
          heatindex_f: 76.8,
          dewpoint_c: 12.8,
          dewpoint_f: 55.0,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 2.5,
          gust_kph: 4.0,
          uv: 6.0,
        },
        {
          time_epoch: 1691683200,
          time: "2023-08-10 18:00",
          temp_c: 22.4,
          temp_f: 72.3,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 2.5,
          wind_kph: 4.0,
          wind_degree: 4,
          wind_dir: "N",
          pressure_mb: 1021.0,
          pressure_in: 30.14,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 56,
          cloud: 6,
          feelslike_c: 24.6,
          feelslike_f: 76.3,
          windchill_c: 22.4,
          windchill_f: 72.3,
          heatindex_c: 24.6,
          heatindex_f: 76.3,
          dewpoint_c: 13.2,
          dewpoint_f: 55.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 3.4,
          gust_kph: 5.4,
          uv: 6.0,
        },
        {
          time_epoch: 1691686800,
          time: "2023-08-10 19:00",
          temp_c: 20.9,
          temp_f: 69.6,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 2.9,
          wind_kph: 4.7,
          wind_degree: 12,
          wind_dir: "NNE",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 66,
          cloud: 7,
          feelslike_c: 20.9,
          feelslike_f: 69.6,
          windchill_c: 20.9,
          windchill_f: 69.6,
          heatindex_c: 20.9,
          heatindex_f: 69.6,
          dewpoint_c: 14.4,
          dewpoint_f: 57.9,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 4.5,
          gust_kph: 7.2,
          uv: 6.0,
        },
        {
          time_epoch: 1691690400,
          time: "2023-08-10 20:00",
          temp_c: 18.6,
          temp_f: 65.5,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 3.6,
          wind_kph: 5.8,
          wind_degree: 43,
          wind_dir: "NE",
          pressure_mb: 1021.0,
          pressure_in: 30.16,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 74,
          cloud: 9,
          feelslike_c: 18.6,
          feelslike_f: 65.5,
          windchill_c: 18.6,
          windchill_f: 65.5,
          heatindex_c: 18.6,
          heatindex_f: 65.5,
          dewpoint_c: 13.8,
          dewpoint_f: 56.8,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 7.2,
          gust_kph: 11.5,
          uv: 5.0,
        },
        {
          time_epoch: 1691694000,
          time: "2023-08-10 21:00",
          temp_c: 17.6,
          temp_f: 63.7,
          is_day: 1,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 73,
          wind_dir: "ENE",
          pressure_mb: 1021.0,
          pressure_in: 30.16,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 78,
          cloud: 6,
          feelslike_c: 17.6,
          feelslike_f: 63.7,
          windchill_c: 17.6,
          windchill_f: 63.7,
          heatindex_c: 17.6,
          heatindex_f: 63.7,
          dewpoint_c: 13.6,
          dewpoint_f: 56.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.4,
          gust_kph: 15.1,
          uv: 5.0,
        },
        {
          time_epoch: 1691697600,
          time: "2023-08-10 22:00",
          temp_c: 17.1,
          temp_f: 62.8,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 92,
          wind_dir: "E",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 80,
          cloud: 7,
          feelslike_c: 17.1,
          feelslike_f: 62.8,
          windchill_c: 17.1,
          windchill_f: 62.8,
          heatindex_c: 17.1,
          heatindex_f: 62.8,
          dewpoint_c: 13.6,
          dewpoint_f: 56.5,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.4,
          gust_kph: 15.1,
          uv: 1.0,
        },
        {
          time_epoch: 1691701200,
          time: "2023-08-10 23:00",
          temp_c: 16.9,
          temp_f: 62.4,
          is_day: 0,
          condition: {
            text: "Clear",
            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
            code: 1000,
          },
          wind_mph: 4.5,
          wind_kph: 7.2,
          wind_degree: 113,
          wind_dir: "ESE",
          pressure_mb: 1021.0,
          pressure_in: 30.15,
          precip_mm: 0.0,
          precip_in: 0.0,
          humidity: 81,
          cloud: 8,
          feelslike_c: 16.9,
          feelslike_f: 62.4,
          windchill_c: 16.9,
          windchill_f: 62.4,
          heatindex_c: 16.9,
          heatindex_f: 62.4,
          dewpoint_c: 13.7,
          dewpoint_f: 56.7,
          will_it_rain: 0,
          chance_of_rain: 0,
          will_it_snow: 0,
          chance_of_snow: 0,
          vis_km: 10.0,
          vis_miles: 6.0,
          gust_mph: 9.4,
          gust_kph: 15.1,
          uv: 1.0,
        },
      ],
    },
  ],
};
